apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymoose-deployment
  labels:
    app: anonymoose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anonymoose
  template:
    metadata:
      labels:
        app: anonymoose
    spec:
      containers:
      - name: anonymoose
        image: evilgenius13/anonymoose:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 9292
        env:
        - name: MEMCACHED_ADDRESS
          value: "memcached:11211"
        - name: MEMCACHED_USERNAME
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: memcached-username
        - name: MEMCACHED_PASSWORD
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: memcached-password
        - name: AXIOM_DATASET
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: axiom-dataset
        - name: AXIOM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: axiom-api-token
        - name: S3_ENDPOINT
          value: "http://minio:9000"
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: s3-region
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: s3-access-key-id
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: s3-secret-access-key
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: s3-bucket
        
