apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: minio-root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: memcached-secrets
              key: minio-root-password
        volumeMounts:
        - name: minio-data
          mountPath: /data
        - name: minio-config
          mountPath: /root/.minio
        command: ["server", "/data", "--console-address", ":9001"]
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data-pvc
      - name: minio-config
        persistentVolumeClaim:
          claimName: minio-config-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP