require 'dotenv/load'

MEMCACHED_ADDRESS = ENV['MEMCACHED_ADDRESS'] || 'localhost:11211'
MEMCACHED_USERNAME = ENV['MEMCACHED_USERNAME']
MEMCACHED_PASSWORD = ENV['MEMCACHED_PASSWORD']
UPLOAD_DIR = ENV['UPLOAD_DIR'] || './uploads'
ENVIRONMENT = ENV['RACK_ENV'] || 'development'
AXIOM_DATASET = ENV['AXIOM_DATASET']
AXIOM_API_TOKEN = ENV['AXIOM_API_TOKEN']