require 'dotenv/load'

MEMCACHED_ADDRESS = ENV['MEMCACHED_ADDRESS'] || 'localhost:11211'
MEMCACHED_USERNAME = ENV['MEMCACHED_USERNAME'] || 'dev'
MEMCACHED_PASSWORD = ENV['MEMCACHED_PASSWORD'] || 'dev'
UPLOAD_DIR = ENV['UPLOAD_DIR'] || './uploads'