steps:
  - label: ":rocket: Deploy"
    commands:
      - git clone https://github.com/EvilGenius13/Anonymoose.git
      - cd Anonymoose
      - scripts/deploy.sh
    env:
      KUBECONFIG: /home/ubuntu/.kube/config
    key: "deploy-step"

  - label: ":satellite: Notify Discord"
    depends_on: "deploy-step"
    commands:
      - |
        if [ "${BUILDKITE_COMMAND_EXIT_STATUS}" -eq 0 ]; then
          curl -X POST "${DISCORD_WEBHOOK_URL}" \
          -H "Content-Type: application/json" \
          -d '{"content": "Deployment successful :rocket:"}'
        else
          curl -X POST "${DISCORD_WEBHOOK_URL}" \
          -H "Content-Type: application/json" \
          -d '{"content": "Deployment failed :x:"}'
