steps:
  - label: ":rocket: Deploy"
    commands:
      - git clone https://github.com/EvilGenius13/Anonymoose.git
      - cd Anonymoose
      - scripts/deploy.sh
    key: "deploy-step"

  - wait:
    continue_on_failure: true

  - label: "Send Discord Notification"
    command: |
      if [ "$(buildkite-agent step get "outcome" --step "deploy-step")" == "passed" ]; then
        curl -X POST "${DISCORD_WEBHOOK_URL}" \
        -H "Content-Type: application/json" \
        -d '{"content": "Deployment successful :rocket:"}'
      else
        curl -X POST "${DISCORD_WEBHOOK_URL}" \
        -H "Content-Type: application/json" \
        -d '{"content": "Deployment failed :x:"}'
      fi
