# Testing
steps:
  - label: ":rocket: Deploy"
    commands:
      - git clone https://github.com/EvilGenius13/Anonymoose.git
      - cd Anonymoose
      - scripts/deploy.sh
      - |
        # Capture the exit status and store it in metadata
        exit_status=$?
        buildkite-agent meta-data set "deploy-exit-status" "$exit_status"
    env:
      KUBECONFIG: /home/ubuntu/.kube/config
    key: "deploy-step"

  - label: ":satellite: Notify Discord"
    depends_on: "deploy-step"
    commands:
      - |
        # Get the exit status from the previous step
        exit_status=$(buildkite-agent meta-data get "deploy-exit-status")
        if [ "$exit_status" -eq 0 ]; then
          curl -X POST "${DISCORD_WEBHOOK_URL}" \
          -H "Content-Type: application/json" \
          -d '{"content": "Deployment successful :rocket:"}'
        else
          curl -X POST "${DISCORD_WEBHOOK_URL}" \
          -H "Content-Type: application/json" \
          -d '{"content": "Deployment failed :x:"}'
