steps:
  - label: ":rocket: Deploy"
    commands:
      - git clone https://github.com/EvilGenius13/Anonymoose.git
      - cd Anonymoose
      - scripts/deploy.sh
    env:
      KUBECONFIG: /home/ubuntu/.kube/config
notify:
  - webhook: "${DISCORD_WEBHOOK_URL}"