steps:
  - label: ":rocket: Deploy"
    commands:
      - git clone https://github.com/EvilGenius13/Anonymoose.git
      - cd Anonymoose
      - scripts/deploy.sh
      - |
        EXIT_STATUS=$?
        echo "Buildkite command exit status: $EXIT_STATUS"
        if [ "$EXIT_STATUS" -eq 0 ]; then
          curl -X POST "${DISCORD_WEBHOOK_URL}" \
          -H "Content-Type: application/json" \
          -d '{"content": "Deployment successful :rocket:"}'
        else
          curl -X POST "${DISCORD_WEBHOOK_URL}" \
          -H "Content-Type: application/json" \
          -d '{"content": "Deployment failed :x:"}'
        fi
    env:
      KUBECONFIG: /home/ubuntu/.kube/config
