steps:
  - label: ":rocket: Deploy"
    commands:
      - git clone https://github.com/EvilGenius13/Anonymoose.git
      - cd repo
      - ./scripts/deploy.sh
    env:
      KUBECONFIG: ~/.kube/config
