services:
  memcached:
    image: bitnami/memcached:latest
    ports:
      - "11211:11211"
    environment:
      MEMCACHED_USERNAME: dev
      MEMCACHED_PASSWORD: dev

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: development
      MINIO_ROOT_PASSWORD: development
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data --console-address ":9001"
