name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
     
      - name: Minio Deploy
        uses: infleet/minio-action@v0.0.1
        with:
          username: 'development'
          password: 'development'
          port: 9000
      
      - name: Wait for Minio to start
        run: |
          while ! curl -s http://localhost:9000/healthcheck > /dev/null; do
            echo "Waiting for Minio to start..."
            sleep 5
          done

      - name: Run tests
        env:
          MEMCACHED_ADDRESS: localhost:11211
          MEMCACHED_USERNAME: ''
          MEMCACHED_PASSWORD: ''
          MINIO_ENDPOINT: http://localhost:9000
          MINIO_ACCESS_KEY: development
          MINIO_SECRET_KEY: development
          SERVER: falcon
          RACK_ENV: test
        run: |
          bundle exec rake test

      

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: evilgenius13/anonymoose:dev
