name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
      minio:
        image: quay.io/minio/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: development
          MINIO_SECRET_KEY: development
        options: --name minio --health-cmd "curl -f http://localhost:9000/minio/health/live" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        env:
          MEMCACHED_ADDRESS: localhost:11211
          MEMCACHED_USERNAME: ''
          MEMCACHED_PASSWORD: ''
          S3_ENDPOINT: http://localhost:9000
          S3_REGION: us-east-1
          S3_ACCESS_KEY_ID: development
          S3_SECRET_ACCESS_KEY: development
          S3_BUCKET: test-bucket
        run: |
          bundle exec rake test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: evilgenius13/anonymoose:dev
