name: PRODUCTION-CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        env:
          MEMCACHED_ADDRESS: localhost:11211
          MEMCACHED_USERNAME: ''
          MEMCACHED_PASSWORD: ''
        run: |
          bundle exec rake test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t evilgenius13/anonymoose:prod .
          docker push evilgenius13/anonymoose:prod

      - name: Notify Buildkite
        if: success()
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.BUILDKITE_API_TOKEN }}" \
            -d '{"build": {"message": "Triggering Buildkite pipeline"}}' \
            https://api.buildkite.com/v2/organizations/timewellspent/pipelines/deployment/builds
